language: python
python:
  - "3.4"
  # PyPy versions
  - "pypy3" # Pypy3 2.4.0
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: pytest

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "eu-west-2"
  app: "hello-world"
  env: "hello-world-dev"
  bucket_name: "elasticbeanstalk-eu-west-2-114600705412"
  on:
    branch: master
