language: python
python:
  - "3.4"
  # PyPy versions
  - "pypy3" # Pypy3 2.4.0
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest discover tests/

after_success:
  - pip install awscli --upgrade
  - pip install awsebcli --upgrade
  - eb init hello-world -r eu-west-2 -p docker-17.06.2-ce
  - eb deploy hello-world-dev
  - eb status hello-world-dev
