language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest discover tests/

# Manual deployment and installation of software
#
#after_success:
#  - pip install awscli --upgrade
#  - pip install awsebcli --upgrade
#  - eb init hello-world -r eu-west-2 -p docker-17.06.2-ce
#  - eb deploy hello-world-dev
#  - eb status hello-world-dev

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  app: $APPLICATION_NAME
  env: $APPLICATION_ENV
  bucket_name: $AWS_S3_BUCKET
